### ISSUE TITLE
Getting gyp ERR! build error  while running command sudo sh build.sh

### ISSUE THREAD

**Issue by pascolan** [AgoraIO/Basic-Recording#28]
**Getting gyp ERR! build error  while running command sudo sh build.sh**
Logs:
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /Users/dhruvkaushal/PASCOLAN AE/assets/Basic-Recording-master/On-Premise-Recording-Nodejs/record/src
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

**Comment by jonchoi** [comment]
Does the node recording server implantation not work?
