### ISSUE TITLE
It shows cannot find module './agorasdk'

### ISSUE THREAD

**Issue by dhavalsojitra8866** [AgoraIO/Basic-Recording#4]
>>node app.js
module.js:549
    throw err;
    ^

Error: Cannot find module './agorasdk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Teenpatti\Agora\Agora-Restful-Recording-Nodejs\record\AgoraRecordSdk.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by plutoless** [comment]
@dhavalsojitra8866 please follow the readme guide to compile a agorasdk.node file first.

**Comment by dhavalsojitra8866** [comment]
@plutoless I went through readme guide and got solved my query.Thank you
