### ISSUE TITLE
Error: recorder not exists

### ISSUE THREAD

**Issue by VladimirCores** [AgoraIO/Basic-Recording#44]
After successful built of SDK for nodejs 12, running start resulted in:
```
0|app  | setting mix layout...
0|app  | joinChannel...
0|app  | appliteDir 
0|app  | /home/vladimir/agora-recording/record/src/sdk/bin/
0|app  | pRecording->m_agorasdk->createChannel return result:
0|app  | 1
0|app  | Error: 101,with stat_code:1
0|app  | sdk stopped due to err code: 101 stat: 1
0|app  | stop recorder APP_ID CHANNEL_ID KEY
0|app  | Error: recorder not exists
0|app  |     at RecordManager.onCleanup (/home/vladimir/agora-recording/server/recordManager.js:154:19)
0|app  |     at AgoraRecordSdk.<anonymous> (/home/vladimir/agora-recording/server/recordManager.js:72:18)
0|app  |     at AgoraRecordSdk.emit (events.js:327:22)
0|app  |     at Immediate.<anonymous> (/home/vladimir/agora-recording/record/AgoraRecordSdk.js:18:18)
0|app  |     at processImmediate (internal/timers.js:456:21)
```

**Comment by VladimirCores** [comment]
And looks like the same thing is happening for node 10 version:
```
vladimir@agora-recording-instance:~/Basic-Recording/On-Premise-Recording-Nodejs/record$ node sdkdemo.js 
setting mix layout...
joinChannel...
appliteDir /home/vladimir/Basic-Recording/On-Premise-Recording-Nodejs/record/src/sdk/bin/
pRecording->m_agorasdk->createChannel return result:1
Error: 110,with stat_code:1
err 110 1
(node:7571) UnhandledPromiseRejectionWarning: 110
(node:7571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
 inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
(rejection id: 1)
(node:7571) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejec
tions that are not handled will terminate the Node.js process with a non-zero exit code.
leaveChannel...
```

**Comment by VladimirCores** [comment]
Here is log, but with something different:
```
Local Date: Sat Oct  3 12:53:55 2020
Build info: Sep 17 2020 06:42:56 ?

INFO    (12:53:55:727 |    0)   1888; [rp] {"rtc.video.mute_me":true,"che.video.local.send":false}
INFO    (12:53:55:727 |    0)   1888; [rp] {"rtc.audio.mute_me":true,"che.audio.mute_me":true}
INFO    (12:53:55:727 |    0)   1888; [rp] {"rtc.video.set_remote_default_video_stream_type":0}
INFO    (12:53:55:727 |    0)   1888; API call to SetRemoteDefaultVideoStreamType: 0
INFO    (12:53:55:727 |    0)   1888; [rp] {"che.video.local.camera_index":1024}
INFO    (12:53:55:727 |    0)   1888; [rp] {"rtc.video.enabled":true}
INFO    (12:53:55:727 |    0)   1888; API call to enable video
INFO    (12:53:55:727 |    0)   1888; [rp] {"che.video.recording":false}
INFO    (12:53:55:727 |    0)   1888; doStopLastmileProbeTest
INFO    (12:53:55:727 |    0)   1888; ***CALL BEGIN: appid:'45****************************69' cname:'agoratest' info:'' sid:'5E3A234D6D17436EBA765E597F64AFA5'
INFO    (12:53:55:727 |    0)   1888; addRef of media engine, ref=1
INFO    (12:53:55:727 |    0)   1888; [che] create chat engine, ctx:(nil)
INFO    (12:53:55:727 |    0)   1888; [MYDEBUG] large group call false
INFO    (12:53:55:727 |    0)   1888; ChatEngineParameterHelper::applyMediaEngineMode: 
INFO    (12:53:55:727 |    0)   1888; applyMediaEngineMode(): 264_Hardware decoding false,265_Hardware decoding true
INFO    (12:53:55:728 |    1)   1890; Thread with name:AudioAsyncTask started 
INFO    (12:53:55:728 |    0)   1888; engine git commit version:44332b9 and branch:(no
INFO    (12:53:55:728 |    0)   1888; audio jitterbuffer new smooth
INFO    (12:53:55:728 |    0)   1891; Thread with name:AudioFileDecoderThread started 
INFO    (12:53:55:728 |    0)   1888; OutputMixer: start audio file decoder thread successfully
INFO    (12:53:55:728 |    0)   1892; Thread with name:external_audio_module_thread started 
INFO    (12:53:55:728 |    0)   1893; Thread with name:WebRtc_event_timer_thread started 
INFO    (12:53:55:728 |    0)   1888; StereoPlayoutIsAvailable(), output: available=0
INFO    (12:53:55:728 |    0)   1888; StereoRecordingIsAvailable(), output: available=0
INFO    (12:53:55:728 |    0)   1894; Thread with name:EngineMonitorThread started 
INFO    (12:53:55:728 |    0)   1888; setMuteStatus, muted: On
INFO    (12:53:55:728 |    0)   1888; setMuteOutput, muted: false
INFO    (12:53:55:728 |    0)   1888; Audio Engine Init success
INFO    (12:53:55:728 |    0)   1888; Available number of cores:16
INFO    (12:53:55:728 |    0)   1888; PipelineManager::SetDest  engine = 0x7f623810fea0
INFO    (12:53:55:728 |    0)   1888; CreateVideoSendTrack
INFO    (12:53:55:728 |    0)   1895; Thread with name:VideoAsyncTask started 
INFO    (12:53:55:728 |    0)   1888; init: feature prerotation disabled
INFO    (12:53:55:728 |    0)   1888; Agora Engine video codec set to standard mode role mode 3
INFO    (12:53:55:728 |    0)   1888; Agora Engine video codec index 1
INFO    (12:53:55:728 |    0)   1888; Agora Engine video stream type = 0
INFO    (12:53:55:729 |    1)   1896; Thread with name:VideoEncodeThread started 
INFO    (12:53:55:729 |    0)   1888; Device type: 0
INFO    (12:53:55:729 |    0)   1888; Hardware encoding false
INFO    (12:53:55:729 |    0)   1888; last unique frame idx: -1 - -1
INFO    (12:53:55:729 |    0)   1888; Device type: 0
INFO    (12:53:55:729 |    0)   1888; EncoderWrapper::Create hardware_ = 0, hardware_low_ = 0
INFO    (12:53:55:729 |    0)   1888; low stream codec type = 1
INFO    (12:53:55:729 |    0)   1888; low bit rate limit 0
INFO    (12:53:55:729 |    0)   1888; dont need to increase unique frame idx
INFO    (12:53:55:729 |    0)   1888; the init unique frame idx: -1 - -1
INFO    (12:53:55:729 |    0)   1897; Thread with name:VideoProcessThread started 
INFO    (12:53:55:729 |    0)   1888; h264WebInteropEnable: enable 0
INFO    (12:53:55:729 |    0)   1888; setCaptureDevice: index=1024
INFO    (12:53:55:729 |    0)   1895; _setCodec: index=1 width=640 height=360 framerate=15
INFO    (12:53:55:729 |    0)   1895; _setCodec: Intra Request = 0
INFO    (12:53:55:739 |   10)   1898; Thread with name:VideoEncodeThread started 
INFO    (12:53:55:739 |    0)   1895; Device type: 0
INFO    (12:53:55:739 |    0)   1895; Hardware encoding false
INFO    (12:53:55:739 |    0)   1895; last unique frame idx: -1 - -1
INFO    (12:53:55:739 |    0)   1895; Device type: 0
INFO    (12:53:55:739 |    0)   1895; EncoderWrapper::Create hardware_ = 0, hardware_low_ = 0
INFO    (12:53:55:739 |    0)   1895; low stream codec type = 1
INFO    (12:53:55:739 |    0)   1895; low bit rate limit 3
INFO    (12:53:55:739 |    0)   1895; set last big unique frame idx: -1
INFO    (12:53:55:739 |    0)   1895; set last small unique frame idx: -1
INFO    (12:53:55:739 |    0)   1895; the init unique frame idx: -1 - -1
INFO    (12:53:55:740 |    1)   1889; [dns] parsed ip 172.217.23.196
INFO    (12:53:55:742 |    2)   1889; [dns] parsed ip 104.193.88.77
INFO    (12:53:55:742 |    0)   1889; [dns] parsed ip 104.193.88.123
INFO    (12:53:55:750 |    8)   1889; [dns] parsed ip 18.195.199.4
INFO    (12:53:55:750 |    0)   1889; [dns] parsed ip 148.153.116.175
INFO    (12:53:55:750 |    0)   1889; [dns] parsed ip 128.1.78.146
INFO    (12:53:55:750 |    0)   1889; [dns] parsed ip 3.9.229.6
INFO    (12:53:55:750 |    0)   1889; [dns] parsed ip 128.1.77.34
INFO    (12:53:55:829 |   79)   1888; blocking isCapturing() 100 ms
INFO    (12:53:55:829 |    0)   1888; VideoSendTrackImpl::UpdateCapturer capturer=0x7f6238131220
INFO    (12:53:55:829 |    0)   1888; CreateVideoCapturer: interface=0x7f6238131220
INFO    (12:53:55:829 |    0)   1888; setMaxVideoBitrate: max bitrate=0
INFO    (12:53:55:829 |    0)   1888; Setting video fec method 2, real using 2
INFO    (12:53:55:829 |    0)   1888; SetBandwidthAgressiveLevel to 3.
INFO    (12:53:55:829 |    0)   1888; dynamic sending rate control set to 2.

INFO    (12:53:55:829 |    0)   1888; videoEngine created and initialize here
INFO    (12:53:55:829 |    0)   1888; CreateVideoSendTrack
INFO    (12:53:55:829 |    0)   1888; [MIO] updateCapturer: ((nil)), type:(1)
INFO    (12:53:55:829 |    0)   1888; CreateAgoraDefaultCapture: type=0
INFO    (12:53:55:829 |    0)   1888; VideoSendTrackImpl::UpdateCapturer capturer=0x7f6238131070
INFO    (12:53:55:829 |    0)   1888; CreateVideoCapturer: interface=0x7f6238131070
INFO    (12:53:55:829 |    0)   1888; [MIO] updateLocalRender: ((nil)), type:(1)
INFO    (12:53:55:829 |    0)   1888; CreateAgoraDefaultRender
INFO    (12:53:55:829 |    0)   1888; VideoSendTrackImpl::UpdateRenderer, renderer=0x7f6238163790
INFO    (12:53:55:829 |    0)   1888; CreateVideoRenderer: interface=0x7f6238163790
INFO    (12:53:55:829 |    0)   1888; [MIO] video send track prepared !!
INFO    (12:53:55:829 |    0)   1888; VideoSendTrackImpl::UpdateCapturer capturer=0x7f6238131220
INFO    (12:53:55:829 |    0)   1888; CreateVideoCapturer: interface=0x7f6238131220
INFO    (12:53:55:829 |    0)   1888; [che] applyVideoProfile: 640x480 15 fps  -1 minFps 1000 kbps, min -1 kbps orientationMode 1 degradationPrefer 0
INFO    (12:53:55:829 |    0)   1888; validateVideoParameters: validate video parameters resolution 640x480, fps 15, rate 1000000
INFO    (12:53:55:829 |    0)   1888; setMaxVideoBitrate: max bitrate=1000000
INFO    (12:53:55:829 |    0)   1888; setCodecRates: set frame rate to 15
INFO    (12:53:55:829 |    0)   1888; setCodecResolution: set to 640 x 480
INFO    (12:53:55:829 |    0)   1888; Set broadcast min br to -1.
INFO    (12:53:55:829 |    0)   1888; [che] chat engine initialized
INFO    (12:53:55:829 |    0)   1888; [time] process EngineInitialize takes 102
INFO    (12:53:55:829 |    0)   1895; _setCodec: index=1 width=640 height=480 framerate=15
INFO    (12:53:55:829 |    0)   1895; _setCodec: Intra Request = 0
INFO    (12:53:55:830 |    1)   1888; [vocs] vocs initialized
WARN    (12:53:55:831 |    1)   1888; create socket error: Operation not permitted
INFO    (12:53:55:831 |    0)   1888; CacheManager: save cache to storage elapsed 0
INFO    (12:53:55:831 |    0)   1888; [cm] emit join channel signal, size=3
INFO    (12:53:55:831 |    0)   1888; [cm] connection state changed from 1 to 2
INFO    (12:53:55:831 |    0)   1888; [vocs] lookup channel...
INFO    (12:53:55:831 |    0)   1888; [vocs] selected: 106.75.133.43:8000
INFO    (12:53:55:831 |    0)   1888; connecting to 106.75.133.43:8000 handle 38193060, 32
INFO    (12:53:55:831 |    0)   1888; [vocs] report bitrate: a/v/t: 50/1000/1050
INFO    (12:53:55:831 |    0)   1888; [vocs] creating channel with 106.75.133.43:8000, ts 1601722435831.......
INFO    (12:53:55:831 |    0)   1888; [vocs] selected: 106.14.12.130:1080
INFO    (12:53:55:831 |    0)   1888; [vocs] report bitrate: a/v/t: 50/1000/1050
INFO    (12:53:55:831 |    0)   1888; [vocs] creating channel with 106.14.12.130:1080, ts 1601722435831.......
INFO    (12:53:55:831 |    0)   1888; [vocs] selected: 52.194.158.59:25000
INFO    (12:53:55:831 |    0)   1888; [vocs] report bitrate: a/v/t: 50/1000/1050
INFO    (12:53:55:831 |    0)   1888; [vocs] creating channel with 52.194.158.59:25000, ts 1601722435831.......
INFO    (12:53:55:832 |    1)   1888; [rp] {"che.video.has_intra_request":false}
INFO    (12:53:55:832 |    0)   1888; [rp] {"che.audio.audioSampleRate":48000}
INFO    (12:53:55:832 |    0)   1888; [dns] parsed ip 3.9.229.6
INFO    (12:53:55:832 |    0)   1888; [dns] parsed ip 128.1.77.34
INFO    (12:53:55:832 |    0)   1888; [dns] parsed ip 18.195.199.4
INFO    (12:53:55:832 |    0)   1888; [dns] parsed ip 148.153.116.175
INFO    (12:53:55:832 |    0)   1888; [dns] parsed ip 128.1.78.146
INFO    (12:53:55:834 |    2)   1888; CacheManager: save cache to storage elapsed 2
INFO    (12:53:55:834 |    0)   1888; [dns] parsed ip 65.255.41.2
INFO    (12:53:55:834 |    0)   1888; [dns] parsed ip 128.1.33.167
INFO    (12:53:55:834 |    0)   1888; [rs] dns parse result code: 0, servers size: 2
INFO    (12:53:55:834 |    0)   1888; [rs] updateServers 65.255.41.2:8000, priority 2
INFO    (12:53:55:834 |    0)   1888; [rs] updateServers 128.1.33.167:8000, priority 2
INFO    (12:53:55:834 |    0)   1888; CacheManager: save cache to storage elapsed 0
INFO    (12:53:55:835 |    1)   1888; [dns] parsed ip 148.153.116.175
INFO    (12:53:55:835 |    0)   1888; [dns] parsed ip 128.1.78.146
INFO    (12:53:55:835 |    0)   1888; [dns] parsed ip 3.9.229.6
INFO    (12:53:55:835 |    0)   1888; [dns] parsed ip 128.1.77.34
INFO    (12:53:55:835 |    0)   1888; [dns] parsed ip 18.195.199.4
INFO    (12:53:55:835 |    0)   1888; [ap] onParsedDns with err 0, 148.153.116.175, 128.1.78.146, 3.9.229.6, 128.1.77.34, 18.195.199.4, 
INFO    (12:53:55:835 |    0)   1888; CacheManager: save cache to storage elapsed 0
INFO    (12:53:55:840 |    5)   1900; Thread with name:VideoEncodeThread started 
INFO    (12:53:55:840 |    0)   1895; Device type: 0
INFO    (12:53:55:840 |    0)   1895; Hardware encoding false
INFO    (12:53:55:840 |    0)   1895; last unique frame idx: -1 - -1
INFO    (12:53:55:840 |    0)   1895; Device type: 0
INFO    (12:53:55:840 |    0)   1895; EncoderWrapper::Create hardware_ = 0, hardware_low_ = 0
INFO    (12:53:55:840 |    0)   1895; low stream codec type = 1
INFO    (12:53:55:840 |    0)   1895; low bit rate limit 671144928
INFO    (12:53:55:840 |    0)   1895; set last big unique frame idx: -1
INFO    (12:53:55:840 |    0)   1895; set last small unique frame idx: -1
INFO    (12:53:55:840 |    0)   1895; the init unique frame idx: -1 - -1
INFO    (12:53:55:840 |    0)   1895; SetTargetWidthHeight width:640, height:480
INFO    (12:53:55:840 |    0)   1888; [dns] parsed ip 35.169.70.181
INFO    (12:53:55:840 |    0)   1888; [dns] parsed ip 184.72.16.87
INFO    (12:53:55:840 |    0)   1888; [dns] parsed ip 3.0.213.60
INFO    (12:53:55:840 |    0)   1888; [dns] parsed ip 164.52.122.53
INFO    (12:53:55:840 |    0)   1888; [dns] parsed ip 148.153.116.174
INFO    (12:53:55:840 |    0)   1888; [dns] parsed ip 52.68.71.190
INFO    (12:53:55:840 |    0)   1888; CacheManager: save cache to storage elapsed 0
INFO    (12:53:55:849 |    9)   1888; [dns] parsed ip 128.1.78.146
INFO    (12:53:55:849 |    0)   1888; [dns] parsed ip 3.9.229.6
INFO    (12:53:55:849 |    0)   1888; [dns] parsed ip 128.1.77.34
INFO    (12:53:55:849 |    0)   1888; [dns] parsed ip 18.195.199.4
INFO    (12:53:55:849 |    0)   1888; [dns] parsed ip 148.153.116.175
INFO    (12:53:55:850 |    1)   1888; CacheManager: save cache to storage elapsed 0
INFO    (12:53:55:924 |   74)   1888; [rlbs/u] responsed from 50.17.126.121:9700 with servers 23.236.96.163:8913
INFO    (12:53:55:924 |    0)   1888; [rs] updateServers 23.236.96.163:8913, priority 3
INFO    (12:53:55:924 |    0)   1888; [rs] updateServers 128.1.233.212:8913, priority 3
INFO    (12:53:55:924 |    0)   1888; [rs] updateServers 148.153.85.194:8913, priority 3
INFO    (12:53:55:940 |   16)   1895; _setCodec: index=1 width=640 height=480 framerate=15
INFO    (12:53:55:940 |    0)   1895; _setCodec: Intra Request = 0
INFO    (12:53:55:950 |   10)   1888; [ap/u] **responsed from 106.75.133.43:8000, CDS(8).
INFO    (12:53:55:950 |    0)   1888; [cs] applied directly: {"configs":{},"version":""}, elapsed: 0
INFO    (12:53:55:950 |    0)   1888; CacheManager: save cache to storage elapsed 0
INFO    (12:53:55:951 |    1)   1888; [ap/u] **responsed from 106.75.133.43:8000, TDS(64).
INFO    (12:53:55:951 |    0)   1888; [ap] onAPTdsRes success with config: {}, size: 0
INFO    (12:53:55:953 |    2)   1888; CacheManager: save cache to storage elapsed 2
INFO    (12:53:55:969 |   16)   1888; [ap/u] **responsed from 106.14.12.130:25000, CDS(8).
INFO    (12:53:55:969 |    0)   1888; [ap/u] **responsed from 106.14.12.130:25000, TDS(64).
INFO    (12:53:56: 14 |    0)   1888; [ap/u] **responsed from 47.244.4.122:1080, CDS(8).
INFO    (12:53:56: 14 |    0)   1888; [ap/u] **responsed from 47.244.4.122:1080, TDS(64).
INFO    (12:53:56: 70 |   56)   1888; [vocs/t] tcp create channel connected with 0x7f6238192ed0
INFO    (12:53:56: 70 |    0)   1888; [vocs] report bitrate: a/v/t: 50/1000/1050
INFO    (12:53:56: 70 |    0)   1888; [vocs] tcp - creating channel with 106.75.133.43:8000, ts 1601722436070.......
ERROR   (12:53:56:213 |  143)   1888; [vocs/u] responsed from 52.194.158.59:25000 with error: 15, elapsed: 488, server ts: 1601722482731. connection aborted
INFO    (12:53:56:214 |    1)   1888; [cm] connection state changed from 2 to 5
INFO    (12:53:56:214 |    0)   1887; Error in mediasdk: 110, (null)
INFO    (12:53:56:214 |    0)   1878; event_loop Required to stop :0
INFO    (12:53:56:214 |    0)   1888; Recording LeaveEvent Argus report.......
WARN    (12:53:56:214 |    0)   1878; Before cleanup cnt 0, errno 11 4, joined_ 0, term_sig 0, leave path code 16
INFO    (12:53:56:214 |    0)   1878; Leaving channel and ready to cleanup
INFO    (12:53:56:215 |    1)   1888; [rp] {"rtc.audio.mute_peers":true}
INFO    (12:53:56:215 |    0)   1888; [rp] {"rtc.video.mute_peers":true}
INFO    (12:53:56:215 |    0)   1878; API call to leave channel
WARN    (12:53:56:215 |    0)   1888; leaving channel that was not joined yet
INFO    (12:53:56:215 |    0)   1888; [cm] emit leave channel signal
INFO    (12:53:56:215 |    0)   1888; stopLocalRender
INFO    (12:53:56:215 |    0)   1888; stopLocalRender success
WARN    (12:53:56:215 |    0)   1888; stopCapture: VideoEngine haven't startCapture
INFO    (12:53:56:215 |    0)   1888; stopRemoteRender
INFO    (12:53:56:215 |    0)   1888; [che] stopCall begins
INFO    (12:53:56:215 |    0)   1889; connecting to 172.217.23.196:80 handle 34002450, 18
INFO    (12:53:56:215 |    0)   1888; [che] stop call returns -1, elapsed 0
INFO    (12:53:56:215 |    0)   1888; [time] process EngineStopCall takes 0
INFO    (12:53:56:215 |    0)   1889; connecting to 104.193.88.123:80 handle 34003660, 21
INFO    (12:53:56:215 |    0)   1889; connecting to 128.1.77.34:8000 handle 34007e70, 22
INFO    (12:53:56:215 |    0)   1888; [rs] **report stats: seq: 27, report list size 8, tx/rx: 3777/912, cache size: 0
INFO    (12:53:56:215 |    0)   1888; [rs] report server1: 23.236.96.163:8913
INFO    (12:53:56:215 |    0)   1888; [cm] connection state changed from 5 to 1
INFO    (12:53:56:215 |    0)   1888; **CALL STATS: duration 0s, tx 3.346K bytes, rx 1.915K bytes, total 5.237K bytes
INFO    (12:53:56:216 |    1)   1888; CacheManager: save cache to storage elapsed 0
INFO    (12:53:56:216 |    0)   1888; delRef of media engine, ref=0
INFO    (12:53:56:216 |    0)   1888; [che] chat engine destroying
INFO    (12:53:56:216 |    0)   1888; stopLocalRender
INFO    (12:53:56:216 |    0)   1888; stopLocalRender success
WARN    (12:53:56:216 |    0)   1888; stopCapture: VideoEngine haven't startCapture
INFO    (12:53:56:216 |    0)   1888; stopRemoteRender
INFO    (12:53:56:216 |    0)   1888; [che] stopCall begins
INFO    (12:53:56:216 |    0)   1888; [che] stop call returns -1, elapsed 0
INFO    (12:53:56:216 |    0)   1888; VideoSendTrackImpl::UpdateCapturer capturer=(nil)
INFO    (12:53:56:216 |    0)   1888; CreateVideoCapturer: interface=(nil)
INFO    (12:53:56:216 |    0)   1888; VideoSendTrackImpl::UpdateRenderer, renderer=(nil)
INFO    (12:53:56:216 |    0)   1888; CreateVideoRenderer: interface=(nil)
INFO    (12:53:56:216 |    0)   1888; stopLocalRender: Cannot stop renderer -1 (not exist)
INFO    (12:53:56:216 |    0)   1888; stopRemoteRender
WARN    (12:53:56:216 |    0)   1888; stopCapture: VideoEngine haven't startCapture
INFO    (12:53:56:236 |   20)   1888; PipelineManager::SetDest  engine = (nil)
WARN    (12:53:56:236 |    0)   1888; terminate: VideoEngine haven't init
INFO    (12:53:56:236 |    0)   1888; [DEBUGG] ViERenderManager Destructor, engine_id: 0
INFO    (12:53:56:239 |    3)   1889; [nt/et] tcp connected with 0x7f6234006d60
INFO    (12:53:56:239 |    0)   1889; [nt/et] request voet list......
INFO    (12:53:56:246 |    7)   1888; AgoraCameraCapture::Dispose
INFO    (12:53:56:271 |   25)   1889; [nt/et] add voet ip: 193.118.52.98
INFO    (12:53:56:271 |    0)   1889; [nt/et] add voet ip: 193.118.42.18
INFO    (12:53:56:271 |    0)   1889; [nt/et] add voet ip: 148.153.82.137
INFO    (12:53:56:271 |    0)   1889; [nt/et] test with tcp:193.118.52.98:5888
INFO    (12:53:56:271 |    0)   1889; connecting to 193.118.52.98:5888 handle 3401a0d0, 18
INFO    (12:53:56:271 |    0)   1889; [nt/et] test with udp:193.118.52.98:5888
INFO    (12:53:56:271 |    0)   1889; socket 22 128.1.77.34:8000 error 11
WARN    (12:53:56:271 |    0)   1889; [nt/et] socket error on tcp 0x7f6234006d60
INFO    (12:53:56:297 |   26)   1888; [che] chat engine destroyed
INFO    (12:53:56:297 |    0)   1888; ***CALL END
INFO    (12:53:56:297 |    0)   1888; onAudioStatusChanged enable audio
INFO    (12:53:56:298 |    1)   1888; [MIO] media io controller destroyed
INFO    (12:53:56:298 |    0)   1878; async task worker thread exited gracefully
```

**Comment by VladimirCores** [comment]
This was a problem of permission on nodejs. Resolved.

**Comment by hvsharma63** [comment]
> This was a problem of permission on nodejs. Resolved.

How did you solve it?
I'm facing this error.

**Comment by BastienLabouche** [comment]
For anyone facing this problem, I had the same with the cpp sample script.

Solved by adding the --channelKey flag followed by a token generated on my agora app profile.
