### ISSUE TITLE
Error installing on node 12.22.10

### ISSUE THREAD

**Issue by Vaibhav-Agarwal06** [AgoraIO/Basic-Recording#52]
We are getting below error when we run **sudo sh build.sh**
OS: ubuntu 18.04
node version: v12.22.10
npm version: 6.14.16

agorasdk.target.mk:119: recipe for target 'Release/obj.target/agorasdk/agora_node_ext/Agor
aSdk.o' failed
make: *** [Release/obj.target/agorasdk/agora_node_ext/AgoraSdk.o] Error 1
make: Leaving directory '/home/ubuntu/record/src/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194
:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:1
2)
gyp ERR! System Linux 4.15.0-1021-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/ubuntu/record/src
gyp ERR! node -v v12.22.10
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
cp: cannot stat 'build/Release/agorasdk.node': No such file or directory

**Comment by anurag-ahead** [comment]
We are getting below error when we run sudo sh build.sh
OS: ubuntu 18.04
node version: v12.22.10
npm version: 6.14.16

agorasdk.target.mk:119: recipe for target 'Release/obj.target/agorasdk/agora_node_ext/Agor
aSdk.o' failed
make: *** [Release/obj.target/agorasdk/agora_node_ext/AgoraSdk.o] Error 1
make: Leaving directory '/home/ubuntu/record/src/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194
:23)
gyp ERR! stack at ChildProcess.emit (events.js:314:20)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:276:1
2)
gyp ERR! System Linux 4.15.0-1021-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/ubuntu/record/src
gyp ERR! node -v v12.22.10
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
cp: cannot stat 'build/Release/agorasdk.node': No such file or directory

**Comment by plutoless** [comment]
hi try using this branch if you are using nodejs12
https://github.com/AgoraIO/Basic-Recording/tree/dev/nodejs12

**Comment by Vaibhav-Agarwal06** [comment]
@plutoless : Thanks. It's working on node version 12.x on Ubuntu OS. Do you have plans to make it compatible to node version 14.x?

We are getting below error when we run "sudo sh build.sh" command on centos on 12.x:
![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/28259777/152747344-4535458c-381d-49a0-a6f0-b1e1ab1cf3a1.png)

**Comment by plutoless** [comment]
@Vaibhav-Agarwal06 i have supported node 14.x in dev/nodejs14 branch
i don't have centOS in hand so if that's not necessary maybe go with ubuntu first.

**Comment by Vaibhav-Agarwal06** [comment]
@plutoless : 
Thanks for prompt support.

Yes, issue has beed fixed for nodejs 14 on Ubuntu.

But some of our client want to setup on centos and don't want to use Ubuntu. Can you please also provide the fix for Centos OS as well.

**Comment by plutoless** [comment]
@Vaibhav-Agarwal06 did you forget to switch branch on your centos system? i tried on centos and it works fine.
